### ISSUE TITLE
[BUG] Can't set event.location in Beacon deactivation event

### ISSUE THREAD

**Issue by Radiation-pi** [SkriptHub/SkBee#5]
### What happened?

[00:01:23] [Server thread/INFO]: Radiation_pi lost connection: Disconnected
[00:01:23] [Server thread/WARN]: [PoaSkRewritev2] could not find glow map, was player injected?: 1211
[00:01:29] [Server thread/ERROR]: #!#! 
[00:01:29] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[00:01:29] [Server thread/ERROR]: #!#! 
[00:01:29] [Server thread/ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[00:01:29] [Server thread/ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[00:01:29] [Server thread/ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[00:01:29] [Server thread/ERROR]: #!#! 
[00:01:29] [Server thread/ERROR]: #!#! Stack trace:
[00:01:29] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Cannot update ticket level while unloading chunks or updating entity manager
[00:01:29] [Server thread/ERROR]: #!#!     at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1314)
[00:01:29] [Server thread/ERROR]: #!#!     at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1303)
[00:01:29] [Server thread/ERROR]: #!#!     at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.scheduleTickingState(ChunkTaskScheduler.java:414)
[00:01:29] [Server thread/ERROR]: #!#!     at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.scheduleChunkLoad(ChunkTaskScheduler.java:597)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.level.ServerChunkCache.syncLoad(ServerChunkCache.java:93)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.level.ServerChunkCache.getChunkFallback(ServerChunkCache.java:125)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:237)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.world.level.Level.getChunk(Level.java:1065)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.world.level.Level.getBlockState(Level.java:1339)
[00:01:29] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.block.CraftBlock.getNMS(CraftBlock.java:78)
[00:01:29] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.block.CraftBlock.getBlockData(CraftBlock.java:171)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.util.Direction.getFacing(Direction.java:224)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.util.BlockUtils.getLocation(BlockUtils.java:89)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.classes.data.BukkitEventValues$10.get(BukkitEventValues.java:281)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.classes.data.BukkitEventValues$10.get(BukkitEventValues.java:277)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:191)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:172)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:97)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.expressions.base.WrapperExpression.get(WrapperExpression.java:89)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:97)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$2(SkriptEventHandler.java:183)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$3(SkriptEventHandler.java:194)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.SkriptEventHandler.execute(SkriptEventHandler.java:192)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:138)
[00:01:29] [Server thread/ERROR]: #!#!     at [S][sk] Skript-2.9.3.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:64)
[00:01:29] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:01:29] [Server thread/ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:71)
[00:01:29] [Server thread/ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[00:01:29] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[00:01:29] [Server thread/ERROR]: #!#!     at org.bukkit.event.Event.callEvent(Event.java:45)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.world.level.block.entity.BeaconBlockEntity.setRemoved(BeaconBlockEntity.java:310)
[00:01:29] [Server thread/ERROR]: #!#!     at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$1.forEach(Object2ObjectOpenHashMap.java:1195)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.world.level.chunk.LevelChunk.clearAllBlockEntities(LevelChunk.java:926)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.level.ServerLevel.unload(ServerLevel.java:1584)
[00:01:29] [Server thread/ERROR]: #!#!     at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.unloadStage2(NewChunkHolder.java:904)
[00:01:29] [Server thread/ERROR]: #!#!     at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processUnloads(ChunkHolderManager.java:1154)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.level.ChunkMap.processUnloads(ChunkMap.java:413)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:404)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:404)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:698)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1833)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:525)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1639)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1326)
[00:01:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[00:01:29] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[00:01:29] [Server thread/ERROR]: #!#! 
[00:01:29] [Server thread/ERROR]: #!#! Version Information:
[00:01:29] [Server thread/ERROR]: #!#!   Skript: 2.9.3 (OUTDATED)
[00:01:29] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[00:01:29] [Server thread/ERROR]: #!#!     Date: 18:47:10.127605400
[00:01:29] [Server thread/ERROR]: #!#!   Bukkit: 1.21.1-R0.1-SNAPSHOT
[00:01:29] [Server thread/ERROR]: #!#!   Minecraft: 1.21.1
[00:01:29] [Server thread/ERROR]: #!#!   Java: 21.0.5 (Java HotSpot(TM) 64-Bit Server VM 21.0.5+9-LTS-jvmci-23.1-b48)
[00:01:29] [Server thread/ERROR]: #!#!   OS: Linux amd64 6.8.0-47-generic
[00:01:29] [Server thread/ERROR]: #!#! 
[00:01:29] [Server thread/ERROR]: #!#! Server platform: Spigot
[00:01:29] [Server thread/ERROR]: #!#! 
[00:01:29] [Server thread/ERROR]: #!#! Current node: null
[00:01:29] [Server thread/ERROR]: #!#! Current item: set {_loc} (as java.lang.Object) to the location
[00:01:29] [Server thread/ERROR]: #!#! Current trigger: beacon deactivation (simple event) (tp.sk, line 105)
[00:01:29] [Server thread/ERROR]: #!#! 
[00:01:29] [Server thread/ERROR]: #!#! Thread: Server thread
[00:01:29] [Server thread/ERROR]: #!#! 
[00:01:29] [Server thread/ERROR]: #!#! Language: simplifiedchinese
[00:01:29] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[00:01:29] [Server thread/ERROR]: #!#! 
[00:01:29] [Server thread/ERROR]: #!#! End of Error.
[00:01:29] [Server thread/ERROR]: #!#! 

### Steps to reproduce

1. Run skbee and Skript on a paper 1.21.1 server
2. Create a new script
3. try to use location in beacon deactivation event

like this:
on beacon deactivation:
    set {_loc] to event-location
    
4. When player log out near to the beacon, the beacon will be unload.
5. This bug has approximately a 10-20% chance of occurring when the player leaves.

### Expected behavior

location can be set to var

### SkBee Version

v3.6.1 (the lastest)

### Server Version

paper 1.21.1

### SkBee Info

[11:42:30 INFO]: --- [Server Info] ---
[11:42:30 INFO]: Server Version: 1.21.1-DEV-972d46c (MC: 1.21.1)
[11:42:30 INFO]: Skript Version: 2.9.3
[11:42:30 INFO]: Skript Addons:
[11:42:30 INFO]: - skript-placeholders v1.6.0
[11:42:30 INFO]: - skript-reflect v2.4
[11:42:30 INFO]: - skript-db v1.4.0
[11:42:30 INFO]: - skript-worldedit v1.1.2
[11:42:30 INFO]: - GravesX v4.9.4.5
[11:42:30 INFO]: - PoaSkRewritev2 v4.10.9
[11:42:30 INFO]: - ItemsAdder v4.0.3
[11:42:30 INFO]: - MythicSkriptAddon v0.99.7
[11:42:30 INFO]: SkBee Version: 3.6.1
[11:42:30 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

### Additional Information

I change the chunk unload time to 6 seconds(10 seconds default).

This bug has approximately a 10-20% chance of occurring when the player leaves, and sometimes it works normally when the player exits.

**Comment by ShaneBeee** [comment]
This isn't related to SkBee at all.

1) `event-location` is from Skript. 

2) The error seems to be an issue with Paper itself. It appears it's trying to grab the location of the block after it's already unloaded.
